# Generated by Django 5.0.4 on 2024-06-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='productos',
            field=models.ManyToManyField(related_name='favoritos', to='tasks.productos'),
        ),
    ]
