# Generated by Django 5.0.4 on 2024-06-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_favoritos_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='tasks.productos'),
        ),
    ]
